/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hakimkalkulator;

/**
 *
 * @author Titik Hidayati
 */
public class tampilankalkulator extends javax.swing.JFrame {

    /**
     * Creates new form tampilankalkulator
     */
    public tampilankalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        out2 = new javax.swing.JTextField();
        out1 = new javax.swing.JTextField();
        out3 = new javax.swing.JTextField();
        hasilnya = new javax.swing.JLabel();
        buttambah = new javax.swing.JButton();
        butkurang = new javax.swing.JButton();
        butkali = new javax.swing.JButton();
        butbagi = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jButton1.setText("jButton1");

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("in1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 50, 22));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("in2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 40, 20));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("in3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("hasil");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));

        out2.setBackground(new java.awt.Color(51, 255, 51));
        out2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out2ActionPerformed(evt);
            }
        });
        getContentPane().add(out2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, 30));

        out1.setBackground(new java.awt.Color(51, 255, 51));
        out1.setFont(new java.awt.Font("Castellar", 0, 11)); // NOI18N
        out1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out1ActionPerformed(evt);
            }
        });
        getContentPane().add(out1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 80, 30));

        out3.setBackground(new java.awt.Color(51, 255, 51));
        out3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out3ActionPerformed(evt);
            }
        });
        getContentPane().add(out3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, 30));

        hasilnya.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        hasilnya.setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().add(hasilnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 80, 40));

        buttambah.setBackground(new java.awt.Color(0, 255, 0));
        buttambah.setText("+");
        buttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttambahActionPerformed(evt);
            }
        });
        getContentPane().add(buttambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 40, 30));

        butkurang.setBackground(new java.awt.Color(0, 255, 0));
        butkurang.setText("-");
        butkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butkurangActionPerformed(evt);
            }
        });
        getContentPane().add(butkurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 40, 30));

        butkali.setBackground(new java.awt.Color(0, 255, 0));
        butkali.setText("x");
        butkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butkaliActionPerformed(evt);
            }
        });
        getContentPane().add(butkali, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 40, 30));

        butbagi.setBackground(new java.awt.Color(0, 255, 0));
        butbagi.setText("/");
        butbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butbagiActionPerformed(evt);
            }
        });
        getContentPane().add(butbagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void out2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_out2ActionPerformed

    private void butkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butkurangActionPerformed
       int ank1, ank2, ank3, hasil;
       ank1 = Integer.parseInt(out1.getText());
       ank2 = Integer.parseInt(out2.getText());
       ank3 = Integer.parseInt(out3.getText());
       hasil = (ank1 - ank2 - ank3);
       hasilnya.setText(String.valueOf(hasil));
       
    }//GEN-LAST:event_butkurangActionPerformed

    private void out1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_out1ActionPerformed

    private void buttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttambahActionPerformed
       int ank1, ank2, ank3, hasil;
       ank1 = Integer.parseInt(out1.getText());
       ank2 = Integer.parseInt(out2.getText());
       ank3 = Integer.parseInt(out3.getText());
       hasil = (ank1 + ank2 + ank3);
       hasilnya.setText(String.valueOf(hasil));
    }//GEN-LAST:event_buttambahActionPerformed

    private void butbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butbagiActionPerformed
       int ank1, ank2, ank3, hasil;
       ank1 = Integer.parseInt(out1.getText());
       ank2 = Integer.parseInt(out2.getText());
       ank3 = Integer.parseInt(out3.getText());
       hasil = (ank1 / ank2 / ank3);
       hasilnya.setText(String.valueOf(hasil));
    }//GEN-LAST:event_butbagiActionPerformed

    private void butkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butkaliActionPerformed
       int ank1, ank2, ank3, hasil;
       ank1 = Integer.parseInt(out1.getText());
       ank2 = Integer.parseInt(out2.getText());
       ank3 = Integer.parseInt(out3.getText());
       hasil = (ank1 * ank2 * ank3);
       hasilnya.setText(String.valueOf(hasil));
    }//GEN-LAST:event_butkaliActionPerformed

    private void out3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_out3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilankalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilankalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilankalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilankalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilankalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butbagi;
    private javax.swing.JButton butkali;
    private javax.swing.JButton butkurang;
    private javax.swing.JButton buttambah;
    private javax.swing.JLabel hasilnya;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField out1;
    private javax.swing.JTextField out2;
    private javax.swing.JTextField out3;
    // End of variables declaration//GEN-END:variables
}
